"""`agmem.sessions`: two hosts' session logs into one trajectory, with the
harness noise gone and the secrets redacted.

Fixtures are synthetic records in the exact shapes observed on 2026-09-02 in
real `~/.claude/projects/*/*.jsonl` and `~/.codex/sessions/**/rollout-*.jsonl`
files (field names, part types, flags). Real sessions are never committed.
"""

from __future__ import annotations

import json

import pytest

from agmem.sessions import (
    HOST_CLAUDE_CODE,
    HOST_CODEX,
    REDACTED,
    TOOL_OUTPUT_MAX_CHARS,
    claude_code_project_key,
    iter_claude_code_sessions,
    iter_codex_sessions,
    load,
    load_claude_code,
    load_codex,
    redact_secrets,
    strip_injected,
)

TS = "2026-09-02T01:00:00.000Z"


def _jsonl(path, records):
    path.write_text("\n".join(json.dumps(r, ensure_ascii=False) for r in records) + "\n")
    return path


def _cc(kind, content, **extra):
    base = {
        "type": kind,
        "uuid": "u",
        "parentUuid": None,
        "isSidechain": False,
        "timestamp": TS,
        "cwd": "/home/u/proj",
        "sessionId": "sess-1",
        "version": "2.1.225",
        "gitBranch": "main",
        "message": {"role": kind, "content": content},
    }
    base.update(extra)
    return base


@pytest.fixture
def claude_session(tmp_path):
    long_output = "x" * (TOOL_OUTPUT_MAX_CHARS * 3)
    records = [
        {"type": "mode", "sessionId": "sess-1"},
        _cc(
            "user",
            "<local-command-caveat>Caveat: generated by the user while running local commands.</local-command-caveat>",
            isMeta=True,
        ),
        _cc(
            "user",
            "<system-reminder>ignore me</system-reminder>Please fix the failing test "
            "<command-name>/foo</command-name>",
        ),
        _cc(
            "assistant",
            [
                {"type": "thinking", "thinking": "private reasoning", "signature": "sig"},
                {"type": "text", "text": "Looking at the test now."},
                {
                    "type": "tool_use",
                    "id": "toolu_1",
                    "name": "Bash",
                    "input": {"command": "pytest -q", "token": "sk-abcdefghijklmnopqrstuvwxyz1234"},
                },
            ],
        ),
        _cc(
            "user",
            [
                {
                    "type": "tool_result",
                    "tool_use_id": "toolu_1",
                    "content": long_output,
                    "is_error": False,
                }
            ],
        ),
        _cc("user", [{"type": "text", "text": "sidechain chatter"}], isSidechain=True),
        _cc("assistant", [{"type": "text", "text": "Fixed. Key was AKIAABCDEFGHIJKLMNOP"}]),
        {"type": "attachment", "attachment": {}},
    ]
    return _jsonl(tmp_path / "abc123.jsonl", records)


def test_claude_code_keeps_the_conversation_and_drops_the_harness(claude_session):
    traj = load_claude_code(claude_session)
    assert traj.host == HOST_CLAUDE_CODE
    assert traj.id == "abc123"
    assert traj.cwd == "/home/u/proj" and traj.git_branch == "main"
    kinds = [s.kind for s in traj.steps]
    assert kinds == ["user", "assistant", "tool_call", "tool_result", "assistant"]
    user = traj.steps[0].text
    assert user == "Please fix the failing test"  # reminder + command wrapper stripped
    assert "private reasoning" not in traj.render()  # thinking dropped
    assert "sidechain chatter" not in traj.render()  # sub-agent chain dropped
    assert "Caveat" not in traj.render()  # isMeta dropped


def test_claude_code_tool_steps_are_linked_named_clipped_and_redacted(claude_session):
    traj = load_claude_code(claude_session)
    call, result = traj.steps[2], traj.steps[3]
    assert call.tool_name == "Bash" and call.tool_call_id == "toolu_1"
    assert "pytest -q" in call.text
    assert "sk-abcdefghijklmnopqrstuvwxyz1234" not in call.text and REDACTED in call.text
    assert result.tool_name == "Bash" and result.tool_call_id == "toolu_1"
    assert len(result.text) <= TOOL_OUTPUT_MAX_CHARS + 40 and "chars omitted" in result.text
    assert result.meta == {"is_error": False}
    assert "AKIAABCDEFGHIJKLMNOP" not in traj.steps[4].text


def _cx(ptype, **payload):
    return {
        "timestamp": TS,
        "ordinal": 1,
        "type": "response_item",
        "payload": {"type": ptype, **payload},
    }


@pytest.fixture
def codex_session(tmp_path):
    records = [
        {
            "timestamp": TS,
            "ordinal": 0,
            "type": "session_meta",
            "payload": {
                "id": "019f-session",
                "session_id": "019f-session",
                "timestamp": TS,
                "cwd": "/home/u/other",
                "cli_version": "0.151.0",
                "source": "cli",
                "thread_source": "user",
                "model_provider": "openai",
            },
        },
        {"timestamp": TS, "type": "turn_context", "payload": {}},
        _cx(
            "message", role="developer", content=[{"type": "input_text", "text": "You are Codex."}]
        ),
        _cx(
            "message",
            role="user",
            content=[
                {"type": "input_text", "text": "<recommended_plugins>x</recommended_plugins>"},
                {"type": "input_text", "text": "Rename the module"},
            ],
        ),
        _cx("reasoning", summary=[{"type": "summary_text", "text": "thinking"}]),
        _cx(
            "custom_tool_call",
            name="exec",
            call_id="call_1",
            input="await tools.exec_command({cmd:'ls'})",
        ),
        _cx(
            "custom_tool_call_output",
            call_id="call_1",
            output=[{"type": "input_text", "text": "a.py\nb.py ghp_abcdefghijklmnopqrstuvwxyz"}],
        ),
        _cx(
            "function_call",
            name="send_message",
            namespace="collaboration",
            call_id="call_2",
            arguments='{"x":1}',
        ),
        _cx("function_call_output", call_id="call_2", output=""),
        _cx("message", role="assistant", content=[{"type": "output_text", "text": "Renamed."}]),
        {"timestamp": TS, "type": "event_msg", "payload": {"type": "token_count"}},
    ]
    return _jsonl(tmp_path / "rollout-2026-09-02T01-00-00-019f-session.jsonl", records)


def test_codex_rollout_maps_to_the_same_shape(codex_session):
    traj = load(codex_session)  # host guessed from the rollout- prefix
    assert traj.host == HOST_CODEX
    assert traj.id == "019f-session" and traj.cwd == "/home/u/other"
    assert traj.meta["thread_source"] == "user" and traj.meta["cli_version"] == "0.151.0"
    kinds = [(s.kind, s.tool_name) for s in traj.steps]
    assert kinds == [
        ("user", None),
        ("tool_call", "exec"),
        ("tool_result", "exec"),
        ("tool_call", "send_message"),
        ("assistant", None),
    ]
    assert traj.steps[0].text == "Rename the module"  # plugin banner stripped
    assert "You are Codex" not in traj.render()  # developer dropped
    assert "thinking" not in traj.render()  # reasoning dropped
    assert REDACTED in traj.steps[2].text  # token in tool output redacted
    # an empty function_call_output produces no step


def test_episodes_carry_provenance_and_render_orders_steps(codex_session):
    traj = load_codex(codex_session)
    episodes = traj.to_episodes(namespace="ns")
    assert [e.role for e in episodes] == [s.kind for s in traj.steps]
    assert all(e.namespace == "ns" for e in episodes)
    first = episodes[0].meta
    assert first["source"] == HOST_CODEX and first["session_id"] == "019f-session"
    assert first["step_index"] == 0 and first["cwd"] == "/home/u/other"
    rendered = traj.render()
    assert (
        rendered.index("[0] USER")
        < rendered.index("[1] TOOL_CALL(exec)")
        < rendered.index("[4] ASSISTANT")
    )
    assert len(traj.render(max_chars=120)) < 200


@pytest.mark.parametrize(
    "raw",
    [
        "token sk-proj-ABCDEFGHIJKLMNOPQRSTUVWXYZ",
        "Authorization: Bearer abcdefghijklmnopqrstuvwxyz0123",
        "export OPENAI_API_KEY=abcdefghijklmnopqrstuvwxyz",
        "-----BEGIN RSA PRIVATE KEY-----\nMIIE\n-----END RSA PRIVATE KEY-----",
        "xoxb-1234567890-abcdefghij",
    ],
)
def test_common_credential_shapes_are_redacted(raw):
    out = redact_secrets(raw)
    assert REDACTED in out
    assert "abcdefghijklmnopqrstuvwxyz" not in out and "MIIE" not in out


def test_strip_injected_returns_empty_when_nothing_was_typed():
    assert (
        strip_injected(
            "<system-reminder>a</system-reminder>\n<task-notification>b</task-notification>"
        )
        == ""
    )
    assert strip_injected("  hello <skill>body</skill> world ") == "hello  world"


def test_discovery_uses_the_hosts_layouts(tmp_path):
    key = claude_code_project_key("/home/u/agentic_memory")
    assert key == "-home-u-agentic-memory"
    cc = tmp_path / ".claude" / "projects" / key
    cc.mkdir(parents=True)
    (cc / "s1.jsonl").write_text("")
    cx = tmp_path / ".codex" / "sessions" / "2026" / "09" / "02"
    cx.mkdir(parents=True)
    (cx / "rollout-2026-09-02T00-00-00-x.jsonl").write_text("")
    assert [p.name for p in iter_claude_code_sessions("/home/u/agentic_memory", home=tmp_path)] == [
        "s1.jsonl"
    ]
    assert [p.name for p in iter_claude_code_sessions(home=tmp_path)] == ["s1.jsonl"]
    assert [p.name for p in iter_codex_sessions(home=tmp_path)] == [
        "rollout-2026-09-02T00-00-00-x.jsonl"
    ]


def test_step_ids_are_deterministic_so_reingesting_a_session_overwrites_itself(codex_session):
    """The ingest path is idempotent because the ids are, not because it keeps a
    ledger: a session read twice yields the same episode ids and the doc store's
    INSERT OR REPLACE turns the second write into a no-op."""
    traj = load_codex(codex_session)
    again = load_codex(codex_session)
    ids = [traj.episode_id(i) for i in range(len(traj.steps))]
    assert ids == [again.episode_id(i) for i in range(len(again.steps))]
    assert len(set(ids)) == len(ids)
    assert all(eid.startswith("sess-") for eid in ids)
    assert [e.id for e in traj.to_episodes()] == ids
    assert [s["episode_id"] for s in traj.as_task_trajectory()] == ids

    # Same index, different session or host: a different id, so two hosts that
    # happen to name a session alike never collide in one store.
    other_host = load_codex(codex_session)
    other_host.host = HOST_CLAUDE_CODE
    assert other_host.episode_id(0) != traj.episode_id(0)
    other_id = load_codex(codex_session)
    other_id.id = "different"
    assert other_id.episode_id(0) != traj.episode_id(0)
