"""Store protocols. All adapters for a slot implement the same interface."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from agmem.core.ops import MemoryOp
from agmem.core.types import Episode


@runtime_checkable
class DocStore(Protocol):
    """Source of truth for raw episodes, derived items, and the op log."""

    def add_episode(self, ep: Episode) -> None: ...
    def get_episodes(self, ids: list[str]) -> list[Episode]: ...
    def count_episodes(self, namespace: str | None = None) -> int: ...
    def search_lexical(self, query: str, k: int = 10,
                       namespace: str | None = None) -> list[tuple[str, float]]: ...

    def put_item(self, item_id: str, memory_type: str, namespace: str,
                 data: dict[str, Any]) -> None: ...
    def get_items(self, ids: list[str], memory_type: str) -> list[dict[str, Any]]: ...

    # EvolutionLog
    def append(self, ops: list[MemoryOp]) -> None: ...
    def tail(self, n: int = 20) -> list[MemoryOp]: ...
    def count(self) -> int: ...

    def close(self) -> None: ...


@runtime_checkable
class VectorStore(Protocol):
    """Embedding index. ``score`` is cosine similarity (higher = closer)."""

    dim: int

    def add(self, item_id: str, embedding: list[float],
            memory_type: str = "episodic", namespace: str = "main") -> None: ...
    def search(self, embedding: list[float], k: int = 10,
               memory_type: str | None = None,
               namespace: str | None = None) -> list[tuple[str, float]]: ...
    def get(self, ids: list[str]) -> dict[str, list[float]]: ...
    def delete(self, ids: list[str]) -> None: ...
    def count(self) -> int: ...
    def persist(self) -> None: ...
    def close(self) -> None: ...
